const fibo = require('.')
const assert = require('assert')
describe('fibonacci < 100', () => {
  it('fibo < 100', () => {
    const r = [...fibo(100)]
    console.log(r.length)
    assert(r[0] === 0)
    assert(r[1] === 1)
    assert(r[2] === 1)
    assert(r[3] === 2)
    assert(r[4] === 3)
    assert(r[5] === 5)
    assert(r[6] === 8)
    assert(r[7] === 13)
    assert(r[8] === 21)
    assert(r[9] === 34)
    assert(r[10] === 55)
    assert(r[11] === 89)
  })
})
